# Generated by Django 3.2.3 on 2021-06-22 04:20

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True,
                 validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('tenant_key', models.CharField(max_length=50, unique=True)),
                ('tenant_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(
                    db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='domains', to='myapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150,
                 unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='isActive')),
                ('is_admin', models.BooleanField(
                    default=False, verbose_name='isAdmin')),
                ('tenant', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
