# Generated by Django 3.2.3 on 2021-06-22 00:12

from django.db import migrations

from myapp.models import Tenant, TenantUser, Domain

def migrate_data(apps, schema_editor):
    #Tenant = apps.get_model('myapp','Tenant')
    #TenantUser = apps.get_model('myapp', 'TenantUser')
    #Domain = apps.get_model('myapp','Domain')

    adt = Tenant.objects.create(schema_name='public', tenant_key='admin', tenant_name='管理')

    TenantUser.objects.create_superuser('admin', password='admin_pass', tenant=adt)

    Domain.objects.create(domain='localhost', tenant=adt, is_primary=True)

def reverse_data(apps, schema_editor):
    #Tenant = apps.get_model('myapp','Tenant')
    #TenantUser = apps.get_model('myapp', 'TenantUser')
    #Domain = apps.get_model('myapp','Domain')

    Domain.objects.filter(domain='localhost').delete()
    TenantUser.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data,
            reverse_code=reverse_data
        ),
    ]
